/* GENERATED by the archlet skill. */
window.ARCH = {
  config: {
    project: "nokori",
    layers: {
      "hot-path": { label: "Hot Path", border: "#e85d04", ink: "#fff", fill: "#fef3e8" },
      "cold-path": { label: "Cold Path", border: "#5e60ce", ink: "#fff", fill: "#f0effa" },
      "engine": { label: "Engine", border: "#0077b6", ink: "#fff", fill: "#e8f4fd" },
      "foundation": { label: "Foundation", border: "#588157", ink: "#fff", fill: "#edf5ed" },
      "interface": { label: "Interface", border: "#9d4edd", ink: "#fff", fill: "#f5edfc" },
      "frontend": { label: "Frontend", border: "#e63946", ink: "#fff", fill: "#fdedef" },
      "external": { label: "External", border: "#6c757d", ink: "#fff", fill: "#f1f1f1" }
    }
  },
  nodes: [
    // ─── Top-level containers ───
    { id: "backend", name: "Backend", g: "foundation", brief: "Python rule memory engine", role: "Core Python package implementing behavioral memory", rt: "nokori/__init__.py", path: "nokori" },
    { id: "frontend-app", name: "Dashboard", g: "frontend", brief: "Web monitoring UI", role: "Vite + React + TypeScript dashboard for rule management and monitoring", rt: "web/src/App.tsx", path: "web" },

    // ─── Hot Path (hook handlers, zero LLM) ───
    { id: "hooks", name: "Hooks", g: "hot-path", parent: "backend", brief: "Hook event handlers", role: "Handles Claude Code / Cursor hook events in the hot path with zero LLM calls", rt: "nokori/hooks/__init__.py", path: "nokori/hooks",
      methods: [
        { name: "handle", src: "nokori/hooks/pre_tool_use.py:296" },
        { name: "_has_tool_evidence", src: "nokori/hooks/pre_tool_use.py:86" },
        { name: "_tool_input_exclusion_fires", src: "nokori/hooks/pre_tool_use.py:124" },
        { name: "try_claim", src: "nokori/hooks/coalesce.py:65" },
        { name: "_is_gate_eligible_rule", src: "nokori/hooks/pre_tool_use.py:41" },
        { name: "coalesce_enabled", src: "nokori/hooks/coalesce.py:24" }
      ]
    },
    { id: "gate", name: "Gate", g: "hot-path", parent: "backend", brief: "Tool-call blocking", role: "Blocks one tool call per prompt for trusted gate-eligible rules, forcing model to read the rule", rt: "nokori/gate/engine.py", path: "nokori/gate",
      methods: [
        { name: "delete", src: "nokori/gate/marker.py:122" },
        { name: "prompt_hash", src: "nokori/gate/marker.py:18" },
        { name: "exists", src: "nokori/gate/prompt_ack.py:34" },
        { name: "should_block", src: "nokori/gate/engine.py:47" },
        { name: "select_gate_rules", src: "nokori/gate/blocker.py:141" },
        { name: "_deferred_dir", src: "nokori/gate/prompt_ack.py:40" }
      ]
    },
    { id: "lifecycle", name: "Lifecycle", g: "hot-path", parent: "backend", brief: "State transitions", role: "Manages rule lifecycle states: candidate → active → trusted / suppressed → archived", rt: "nokori/lifecycle/transitions.py", path: "nokori/lifecycle",
      methods: [
        { name: "_apply_transition", src: "nokori/lifecycle/transitions.py:264" },
        { name: "_recent_trusted_rules_summary", src: "nokori/lifecycle/hot_cache.py:108" },
        { name: "_set_last_run", src: "nokori/lifecycle/maintenance.py:40" },
        { name: "_due", src: "nokori/lifecycle/maintenance.py:50" },
        { name: "find_previous_transcript", src: "nokori/lifecycle/hot_cache.py:20" },
        { name: "maybe_inject", src: "nokori/lifecycle/hot_cache.py:146" }
      ]
    },

    // ─── Engine (search, matching, runtime) ───
    { id: "search", name: "Search", g: "engine", parent: "backend", brief: "BM25 + embedding retrieval", role: "Retrieves rules via BM25 scoring, IDF stats, and optional embedding similarity", rt: "nokori/search/engine.py", path: "nokori/search",
      methods: [
        { name: "tokenize", src: "nokori/search/tokenizer.py:39" },
        { name: "build_idf_stats", src: "nokori/search/idf_stats.py:239" },
        { name: "ping", src: "nokori/search/embed_ipc.py:107" },
        { name: "_reply", src: "nokori/search/embedding_server.py:21" },
        { name: "score", src: "nokori/search/scorer.py:29" },
        { name: "_pid_alive", src: "nokori/search/embed_ipc.py:54" }
      ]
    },
    { id: "matcher", name: "Matcher", g: "engine", parent: "backend", brief: "Rule compilation & eval", role: "Compiles rules into matchers and evaluates trigger/concept/variant matching at runtime", rt: "nokori/matcher/runtime.py", path: "nokori/matcher",
      methods: [
        { name: "evaluate_match", src: "nokori/matcher/runtime.py:382" },
        { name: "compile_rule", src: "nokori/matcher/compiler.py:572" },
        { name: "_tokenize", src: "nokori/matcher/compiler.py:311" },
        { name: "_excluded_context_matches", src: "nokori/matcher/runtime.py:278" },
        { name: "_compile_phrase_pattern", src: "nokori/matcher/compiler.py:328" }
      ]
    },
    { id: "runtime", name: "Runtime", g: "engine", parent: "backend", brief: "Applicability scoring", role: "Evaluates runtime applicability (trigger evidence, IDF policy) to decide HOT/WARM/COLD tier", rt: "nokori/runtime/applicability.py", path: "nokori/runtime",
      methods: [
        { name: "evaluate_applicability", src: "nokori/runtime/applicability.py:236" },
        { name: "meets_min_evidence", src: "nokori/runtime/applicability.py:51" },
        { name: "_select_idf_policy", src: "nokori/runtime/applicability.py:86" },
        { name: "_trigger_info_min", src: "nokori/runtime/applicability.py:221" },
        { name: "_strong_trigger_evidence", src: "nokori/runtime/applicability.py:144" }
      ]
    },

    // ─── Cold Path (background LLM processing) ───
    { id: "cold", name: "Cold Pipeline", g: "cold-path", parent: "backend", brief: "Rule extraction pipeline", role: "Orchestrates the full cold pipeline: extract → qualify → merge → verify → integrate", rt: "nokori/cold/pipeline.py", path: "nokori/cold",
      methods: [
        { name: "validate_role_output", src: "nokori/cold/roles.py:431" },
        { name: "enqueue_job", src: "nokori/cold/jobs.py:43" },
        { name: "resolve_model_id", src: "nokori/cold/roles.py:638" },
        { name: "_pop_first", src: "nokori/cold/roles.py:461" },
        { name: "is_circuit_breaker_open", src: "nokori/cold/jobs.py:133" },
        { name: "mark_job_failed", src: "nokori/cold/jobs.py:105" }
      ]
    },
    { id: "extract", name: "Extract", g: "cold-path", parent: "backend", brief: "Transcript reading", role: "Reads transcripts, compresses them, and feeds extractor LLM to produce candidate rules", rt: "nokori/extract/extractor.py", path: "nokori/extract",
      methods: [
        { name: "extract", src: "nokori/extract/extractor.py:51" },
        { name: "_coerce_str_list", src: "nokori/extract/extractor.py:109" },
        { name: "_coerce_text", src: "nokori/extract/reader.py:249" },
        { name: "read_after", src: "nokori/extract/reader.py:58" },
        { name: "has_cjk", src: "nokori/extract/term_normalize.py:30" },
        { name: "normalize_search_terms", src: "nokori/extract/term_normalize.py:76" }
      ]
    },
    { id: "merge", name: "Merge", g: "cold-path", parent: "backend", brief: "Rule deduplication", role: "Compares new candidates against existing rules, deciding same/broader/narrower/contradicts/unrelated", rt: "nokori/merge/policy.py", path: "nokori/merge",
      methods: [
        { name: "apply_merge_policy", src: "nokori/merge/policy.py:46" },
        { name: "validate_merge_transaction", src: "nokori/merge/policy.py:554" },
        { name: "_lineage", src: "nokori/merge/policy.py:621" },
        { name: "find_merge_neighbors", src: "nokori/merge/policy.py:337" },
        { name: "_keep_both", src: "nokori/merge/policy.py:611" },
        { name: "_len", src: "nokori/merge/policy.py:635" }
      ]
    },
    { id: "posthoc", name: "Posthoc", g: "cold-path", parent: "backend", brief: "Injection evaluation", role: "Judges whether past injections were useful, irrelevant, or harmful using LLM evaluation", rt: "nokori/posthoc/windowing.py", path: "nokori/posthoc",
      methods: [
        { name: "compute_event_window", src: "nokori/posthoc/windowing.py:51" },
        { name: "extract_window_content", src: "nokori/posthoc/windowing.py:114" },
        { name: "_preceded_by_tool_sequence", src: "nokori/posthoc/windowing.py:214" },
        { name: "mark_posthoc_job_complete", src: "nokori/posthoc/jobs.py:78" },
        { name: "mark_posthoc_job_unclear", src: "nokori/posthoc/jobs.py:131" }
      ]
    },
    { id: "eval", name: "Eval", g: "cold-path", parent: "backend", brief: "Synthetic evaluation", role: "Generates synthetic test cases for rules and evaluates them to verify rule quality", rt: "nokori/eval/synthetic.py", path: "nokori/eval",
      methods: [
        { name: "decision_within_max", src: "nokori/eval/synthetic.py:75" },
        { name: "run_synthetic_eval", src: "nokori/eval/synthetic.py:192" },
        { name: "decision_meets_min", src: "nokori/eval/synthetic.py:67" },
        { name: "_evaluate_single_case", src: "nokori/eval/synthetic.py:88" },
        { name: "_case_passes", src: "nokori/eval/synthetic.py:157" },
        { name: "generate_eval_cases_prompt", src: "nokori/eval/synthetic.py:281" }
      ]
    },

    // ─── Foundation (shared core) ───
    { id: "core", name: "Core", g: "foundation", parent: "backend", brief: "DB, config, models", role: "Database access, configuration, data models, and policy definitions shared across all modules", rt: "nokori/db.py", path: "nokori",
      methods: [
        { name: "from_env", src: "nokori/config.py:303" },
        { name: "dumps_json", src: "nokori/db.py:449" },
        { name: "fetchone", src: "nokori/db.py:330" },
        { name: "open_db", src: "nokori/db.py:349" },
        { name: "close", src: "nokori/db.py:309" },
        { name: "transaction", src: "nokori/db.py:313" }
      ]
    },
    { id: "utils", name: "Utils", g: "foundation", parent: "backend", brief: "Shared utilities", role: "Time helpers, host detection, filesystem ops, UUID generation, and hook diagnostics", rt: "nokori/utils/time.py", path: "nokori/utils",
      methods: [
        { name: "now_iso", src: "nokori/utils/time.py:10" },
        { name: "detect_host_from_payload", src: "nokori/utils/host.py:63" },
        { name: "iso_of", src: "nokori/utils/time.py:6" },
        { name: "_trunc", src: "nokori/utils/hook_diag.py:40" },
        { name: "atomic_write_json", src: "nokori/utils/fs.py:10" },
        { name: "effective_session_id", src: "nokori/utils/host.py:38" }
      ]
    },
    { id: "events", name: "Events", g: "foundation", parent: "backend", brief: "Fire & shadow events", role: "Records fire events (injection instances) and shadow events (candidate matches) for observability", rt: "nokori/events/fire.py", path: "nokori/events",
      methods: [
        { name: "create_fire_event", src: "nokori/events/fire.py:15" },
        { name: "write_event", src: "nokori/events/observability.py:21" },
        { name: "count_evaluated_fire_events", src: "nokori/events/fire.py:136" },
        { name: "update_first_observed_useful", src: "nokori/events/fire.py:86" },
        { name: "write_error", src: "nokori/events/observability.py:58" },
        { name: "mark_shadow_label", src: "nokori/events/shadow.py:286" }
      ]
    },
    { id: "archive", name: "Archive", g: "foundation", parent: "backend", brief: "Fingerprint memory", role: "Manages archived fingerprints that block equivalent future rules from being re-admitted", rt: "nokori/archive/fingerprints.py", path: "nokori/archive",
      methods: [
        { name: "_content_tokens", src: "nokori/archive/fingerprints.py:307" },
        { name: "create_archived_fingerprint_from_data", src: "nokori/archive/fingerprints.py:29" },
        { name: "compute_signature", src: "nokori/archive/fingerprints.py:13" },
        { name: "_fingerprint_decision", src: "nokori/archive/fingerprints.py:144" },
        { name: "check_fingerprint_block", src: "nokori/archive/fingerprints.py:82" }
      ]
    },

    // ─── Interface (CLI, Web API) ───
    { id: "commands", name: "CLI Commands", g: "interface", parent: "backend", brief: "CLI subcommands", role: "All nokori CLI subcommands: extract, show, test, add, edit, dismiss, install, health, status, maintain", rt: "nokori/commands/__init__.py", path: "nokori/commands",
      methods: [
        { name: "run", src: "nokori/commands/embed_cmd.py:11" },
        { name: "_json_list", src: "nokori/commands/export_import.py:50" },
        { name: "_manual_trigger_structure", src: "nokori/commands/add.py:42" },
        { name: "_read_json_file", src: "nokori/commands/install.py:305" },
        { name: "_str_len", src: "nokori/commands/export_import.py:40" }
      ]
    },
    { id: "web-server", name: "Web Server", g: "interface", parent: "backend", brief: "FastAPI app", role: "FastAPI application serving the REST API and static frontend assets", rt: "nokori/web/app.py", path: "nokori/web",
      methods: [
        { name: "get_config", src: "nokori/web/deps.py:17" },
        { name: "create_app", src: "nokori/web/app.py:13" },
        { name: "set_config", src: "nokori/web/deps.py:12" },
        { name: "new_write_auth_token", src: "nokori/web/deps.py:27" }
      ]
    },
    { id: "web-api", name: "API Routes", g: "interface", parent: "web-server", brief: "REST endpoints", role: "Route handlers for rules, lifecycle, dashboard, timeline, extract, injections, monitor, config, retrieve", rt: "nokori/web/api/rules.py", path: "nokori/web/api",
      methods: [
        { name: "_rule_to_response", src: "nokori/web/api/rules.py:19" },
        { name: "_scored_to_dict", src: "nokori/web/api/retrieve.py:15" },
        { name: "_find_log_files", src: "nokori/web/api/logs.py:19" },
        { name: "_parse_details", src: "nokori/web/api/extract.py:13" }
      ]
    },

    // ─── Frontend (React dashboard) ───
    { id: "fe-pages", name: "Pages", g: "frontend", parent: "frontend-app", brief: "Route pages", role: "Top-level page components: Dashboard, Rules, Lifecycle, Activity, Config, Extract, Retrieve, Logs", rt: "web/src/pages/Dashboard.tsx", path: "web/src/pages" },
    { id: "fe-components", name: "Components", g: "frontend", parent: "frontend-app", brief: "Shared UI components", role: "Reusable UI: GlassCard, Layout, StatusBadge, FilterPill, AnimatedNumber, TimelineGroup", rt: "web/src/components/Layout.tsx", path: "web/src/components" },
    { id: "fe-lib", name: "Lib", g: "frontend", parent: "frontend-app", brief: "API client & utilities", role: "API client, types, theme, i18n, formatting helpers, and config state management", rt: "web/src/lib/api.ts", path: "web/src/lib" },

    // ─── External ───
    { id: "llm", name: "LLM Adapter", g: "external", parent: "backend", brief: "LLM API interface", role: "Wraps OpenAI-compatible API calls for all cold-path LLM interactions (prompts, roles, JSON parsing)", rt: "nokori/llm/adapter.py", path: "nokori/llm",
      methods: [
        { name: "complete_role", src: "nokori/llm/adapter.py:34" },
        { name: "parse_json_payload", src: "nokori/llm/json_payload.py:82" },
        { name: "_iter_fence_bodies", src: "nokori/llm/json_payload.py:43" },
        { name: "wrap_untrusted", src: "nokori/llm/prompts.py:9" },
        { name: "complete_messages", src: "nokori/llm/adapter.py:46" }
      ]
    },
    { id: "embed-server", name: "Embed Server", g: "external", parent: "backend", brief: "Embedding subprocess", role: "IPC-based embedding server using sentence-transformers for local vector similarity", rt: "nokori/search/embedding_server.py", path: "nokori/search" },

    // ─── External services (not in repo) ───
    { id: "external-llm-api", name: "LLM API", g: "external", brief: "OpenAI-compatible endpoint", role: "External LLM API endpoint for cold-path inference", rt: "", path: "" },
    { id: "external-st-model", name: "ST Model", g: "external", brief: "sentence-transformers", role: "Local sentence-transformers model loaded by embedding server", rt: "", path: "" }
  ],
  edges: [
    // ─── Hot path edges ───
    { s: "hooks", t: "gate", k: "call", l: "should_block / select_gate_rules", src: "nokori/hooks/pre_tool_use.py:296", method: "mechanical" },
    { s: "hooks", t: "search", k: "call", l: "retrieve formal+shadow pool", src: "nokori/hooks/user_prompt_submit.py:1", method: "manual" },
    { s: "hooks", t: "matcher", k: "call", l: "evaluate_match", src: "nokori/hooks/pre_tool_use.py:86", method: "manual" },
    { s: "hooks", t: "runtime", k: "call", l: "evaluate_applicability", src: "nokori/hooks/user_prompt_submit.py:1", method: "manual" },
    { s: "hooks", t: "events", k: "call", l: "create_fire_event", src: "nokori/hooks/user_prompt_submit.py:1", method: "manual" },
    { s: "hooks", t: "utils", k: "call", src: "nokori/hooks/pre_tool_use.py:296", method: "mechanical" },
    { s: "hooks", t: "core", k: "call", l: "from_env / open_db", src: "nokori/hooks/pre_tool_use.py:296", method: "mechanical" },
    { s: "gate", t: "utils", k: "call", src: "nokori/gate/marker.py:18", method: "mechanical" },
    { s: "gate", t: "core", k: "call", l: "fetchone", src: "nokori/gate/engine.py:47", method: "mechanical" },
    { s: "lifecycle", t: "utils", k: "call", src: "nokori/lifecycle/transitions.py:264", method: "mechanical" },
    { s: "lifecycle", t: "events", k: "call", l: "write_event", src: "nokori/lifecycle/transitions.py:264", method: "manual" },

    // ─── Cold path edges ───
    { s: "cold", t: "extract", k: "call", l: "extract", src: "nokori/cold/pipeline.py:227", method: "manual" },
    { s: "cold", t: "merge", k: "call", l: "apply_merge_policy", src: "nokori/cold/integrate.py:34", method: "mechanical" },
    { s: "cold", t: "eval", k: "call", l: "run_synthetic_eval", src: "nokori/cold/pipeline.py:227", method: "mechanical" },
    { s: "cold", t: "llm", k: "call", l: "complete_role", src: "nokori/cold/_llm_call.py:53", method: "mechanical" },
    { s: "cold", t: "matcher", k: "call", l: "compile_rule", src: "nokori/cold/pipeline.py:227", method: "mechanical" },
    { s: "cold", t: "archive", k: "call", l: "check_fingerprint_block", src: "nokori/cold/pipeline.py:227", method: "mechanical" },
    { s: "cold", t: "events", k: "call", l: "write_event / write_error", src: "nokori/cold/pipeline.py:111", method: "mechanical" },
    { s: "cold", t: "search", k: "call", l: "build_idf_stats / tokenize", src: "nokori/cold/pipeline.py:753", method: "mechanical" },
    { s: "cold", t: "core", k: "call", l: "transaction / fetchone / dumps_json", src: "nokori/cold/integrate.py:171", method: "mechanical" },
    { s: "extract", t: "utils", k: "call", src: "nokori/extract/extractor.py:51", method: "mechanical" },
    { s: "merge", t: "search", k: "call", l: "tokenize", src: "nokori/merge/policy.py:337", method: "mechanical" },
    { s: "posthoc", t: "utils", k: "call", src: "nokori/posthoc/windowing.py:51", method: "mechanical" },
    { s: "posthoc", t: "llm", k: "call", l: "complete_role", src: "nokori/posthoc/windowing.py:51", method: "manual" },

    // ─── Engine internal edges ───
    { s: "search", t: "runtime", k: "call", l: "evaluate_applicability", src: "nokori/search/engine.py:1", method: "manual" },
    { s: "search", t: "embed-server", k: "ipc", l: "encode vectors", src: "nokori/search/embed_ipc.py:107", method: "mechanical" },
    { s: "matcher", t: "search", k: "call", l: "tokenize", src: "nokori/matcher/compiler.py:311", method: "manual" },

    // ─── Interface edges ───
    { s: "commands", t: "cold", k: "call", l: "enqueue / circuit_breaker", src: "nokori/commands/extract.py:106", method: "mechanical" },
    { s: "commands", t: "search", k: "call", l: "build_idf_stats / index_rule", src: "nokori/commands/maintain.py:29", method: "mechanical" },
    { s: "commands", t: "extract", k: "call", l: "read_after / compress", src: "nokori/commands/extract.py:106", method: "mechanical" },
    { s: "commands", t: "gate", k: "call", l: "select_gate_rules / write", src: "nokori/commands/install.py:357", method: "mechanical" },
    { s: "commands", t: "lifecycle", k: "call", l: "load_last_byte_offset", src: "nokori/commands/extract.py:106", method: "mechanical" },
    { s: "commands", t: "events", k: "call", l: "count_evaluated_fire_events", src: "nokori/commands/show.py:23", method: "mechanical" },
    { s: "commands", t: "runtime", k: "call", l: "evaluate_applicability", src: "nokori/commands/test.py:15", method: "mechanical" },
    { s: "commands", t: "utils", k: "call", src: "nokori/commands/export_import.py:253", method: "mechanical" },
    { s: "commands", t: "core", k: "call", l: "open_db / close / fetch_rules", src: "nokori/commands/show.py:23", method: "mechanical" },
    { s: "commands", t: "hooks", k: "call", l: "coalesce_enabled", src: "nokori/commands/status.py:52", method: "mechanical" },
    { s: "web-api", t: "gate", k: "call", l: "select_gate_rules", src: "nokori/web/api/rules.py:19", method: "manual" },
    { s: "web-api", t: "lifecycle", k: "call", l: "transitions / maintenance", src: "nokori/web/api/lifecycle.py:1", method: "manual" },
    { s: "web-api", t: "events", k: "call", l: "fire_events / shadow_events", src: "nokori/web/api/lifecycle.py:1", method: "manual" },
    { s: "web-api", t: "core", k: "call", l: "open_db / fetch_rules", src: "nokori/web/api/rules.py:19", method: "manual" },
    { s: "web-server", t: "web-api", k: "mount", l: "APIRouter", src: "nokori/web/app.py:13", method: "mechanical" },

    // ─── Frontend → Backend wire ───
    { s: "fe-lib", t: "web-api", k: "http", l: "REST API calls", src: "web/src/lib/api.ts:1", method: "manual" },
    { s: "fe-pages", t: "fe-lib", k: "import", src: "web/src/pages/Dashboard.tsx:1", method: "mechanical" },
    { s: "fe-pages", t: "fe-components", k: "import", src: "web/src/pages/Dashboard.tsx:1", method: "mechanical" },

    // ─── External wires ───
    { s: "llm", t: "external-llm-api", k: "http", l: "OpenAI-compatible API", src: "nokori/llm/adapter.py:34", method: "manual" },
    { s: "embed-server", t: "external-st-model", k: "load", l: "sentence-transformers model", src: "nokori/search/embedding_server.py:21", method: "manual" }
  ],
  methodEdges: [
    // cold → core
    { sNode: "cold", sMethod: "validate_role_output", tNode: "llm", tMethod: "parse_json_payload", src: "nokori/cold/roles.py:431" },
    { sNode: "cold", sMethod: "enqueue_job", tNode: "core", tMethod: "transaction", src: "nokori/cold/jobs.py:43" },
    // cold → merge
    { sNode: "cold", sMethod: "mark_job_failed", tNode: "events", tMethod: "write_error", src: "nokori/cold/jobs.py:105" },
    // hooks → gate
    { sNode: "hooks", sMethod: "handle", tNode: "gate", tMethod: "should_block", src: "nokori/hooks/pre_tool_use.py:296" },
    { sNode: "hooks", sMethod: "_is_gate_eligible_rule", tNode: "gate", tMethod: "select_gate_rules", src: "nokori/hooks/pre_tool_use.py:41" },
    // commands → search
    { sNode: "commands", sMethod: "run", tNode: "search", tMethod: "build_idf_stats", src: "nokori/commands/maintain.py:29" },
    { sNode: "commands", sMethod: "run", tNode: "core", tMethod: "open_db", src: "nokori/commands/show.py:23" },
    // cold → eval
    { sNode: "cold", sMethod: "_pop_first", tNode: "eval", tMethod: "run_synthetic_eval", src: "nokori/cold/pipeline.py:227" },
    // cold → merge
    { sNode: "cold", sMethod: "_pop_first", tNode: "merge", tMethod: "apply_merge_policy", src: "nokori/cold/integrate.py:34" },
    // search → embed
    { sNode: "search", sMethod: "ping", tNode: "search", tMethod: "_reply", src: "nokori/search/embed_ipc.py:107" },
    // matcher key path
    { sNode: "matcher", sMethod: "compile_rule", tNode: "search", tMethod: "tokenize", src: "nokori/matcher/compiler.py:572" },
    // lifecycle
    { sNode: "lifecycle", sMethod: "_apply_transition", tNode: "events", tMethod: "write_event", src: "nokori/lifecycle/transitions.py:264" }
  ]
};
