"""Config editor schema: field metadata, defaults, and localized labels."""
from __future__ import annotations

from dataclasses import dataclass
from typing import Any, Literal

from .constants import DEFAULT_GATE_MATCHER

FieldType = Literal["bool", "int", "string", "enum", "secret"]
Locale = Literal["zh", "en", "ja"]


@dataclass(frozen=True)
class FieldDef:
    id: str
    path: tuple[str, ...]
    field_type: FieldType
    default: Any
    options: tuple[str, ...] | None = None
    min_value: int | None = None
    read_only: bool = False
    exclusive_group: str | None = None
    exclusive_variant: Literal["local", "remote"] | None = None
    label: dict[Locale, str] = None  # type: ignore[assignment]
    description: dict[Locale, str] = None  # type: ignore[assignment]

    def __post_init__(self) -> None:
        if self.label is None:
            object.__setattr__(self, "label", {})
        if self.description is None:
            object.__setattr__(self, "description", {})


def _f(
    id: str,
    path: tuple[str, ...],
    field_type: FieldType,
    default: Any,
    *,
    options: tuple[str, ...] | None = None,
    min_value: int | None = None,
    read_only: bool = False,
    exclusive_group: str | None = None,
    exclusive_variant: Literal["local", "remote"] | None = None,
    label_zh: str = "",
    label_en: str = "",
    label_ja: str = "",
    desc_zh: str = "",
    desc_en: str = "",
    desc_ja: str = "",
) -> FieldDef:
    return FieldDef(
        id=id,
        path=path,
        field_type=field_type,
        default=default,
        options=options,
        min_value=min_value,
        read_only=read_only,
        exclusive_group=exclusive_group,
        exclusive_variant=exclusive_variant,
        label={"zh": label_zh, "en": label_en, "ja": label_ja},
        description={"zh": desc_zh, "en": desc_en, "ja": desc_ja},
    )


FIELDS: tuple[FieldDef, ...] = (
    _f(
        "data_dir",
        ("data_dir",),
        "string",
        "~/.nokori",
        read_only=True,
        label_zh="数据目录",
        label_en="Data directory",
        label_ja="データディレクトリ",
        desc_zh="规则库与 config.toml 所在路径（只读，请用环境变量 NOKORI_DATA_DIR 修改）",
        desc_en="Rules DB and config.toml location (read-only; use NOKORI_DATA_DIR to change)",
        desc_ja="ルール DB と config.toml の場所（読み取り専用。変更は NOKORI_DATA_DIR）",
    ),
    _f(
        "log_level",
        ("log_level",),
        "enum",
        "warn",
        options=("debug", "info", "warn", "error"),
        label_zh="日志级别",
        label_en="Log level",
        label_ja="ログレベル",
        desc_zh="写入 ~/.nokori/logs/hook.log 等的最低级别",
        desc_en="Minimum level for ~/.nokori/logs/hook.log and related logs",
        desc_ja="~/.nokori/logs/hook.log などの最小ログレベル",
    ),
    _f(
        "max_injection_chars",
        ("max_injection_chars",),
        "int",
        1500,
        min_value=0,
        label_zh="注入字符上限",
        label_en="Max injection characters",
        label_ja="注入最大文字数",
        desc_zh="单次注入规则文本的最大字符数",
        desc_en="Max characters injected per prompt for rule text",
        desc_ja="1 回のプロンプトへ注入するルール文の最大文字数",
    ),
    _f(
        "disabled",
        ("disabled",),
        "bool",
        False,
        label_zh="禁用 Nokori",
        label_en="Disable Nokori",
        label_ja="Nokori を無効化",
        desc_zh="为 true 时所有 hook 空跑",
        desc_en="When true, all hooks no-op",
        desc_ja="true のとき全 hook をスキップ",
    ),
    _f(
        "strict",
        ("strict",),
        "bool",
        False,
        label_zh="严格模式",
        label_en="Strict mode",
        label_ja="厳格モード",
        desc_zh="启用后部分容错行为会更严格",
        desc_en="Tighter behavior for some error paths",
        desc_ja="一部のエラー処理を厳格化",
    ),
    _f(
        "dismiss_phrase",
        ("dismiss_phrase",),
        "string",
        "dismiss",
        label_zh="退役口令",
        label_en="Dismiss phrase",
        label_ja="退役フレーズ",
        desc_zh="在 prompt 中用「短语 + 规则短 ID」退役规则",
        desc_en="Phrase plus rule short ID in prompt to archive a rule",
        desc_ja="プロンプトで「フレーズ + 短 ID」によりルールをアーカイブ",
    ),
    _f(
        "gate.enabled",
        ("gate", "enabled"),
        "bool",
        True,
        label_zh="启用 Gate",
        label_en="Gate enabled",
        label_ja="Gate 有効",
        desc_zh="是否在工具调用前阻断以强制查看规则",
        desc_en="Block tool use until HOT gate rules are acknowledged",
        desc_ja="HOT ルール確認までツール呼び出しをブロック",
    ),
    _f(
        "gate.ttl_seconds",
        ("gate", "ttl_seconds"),
        "int",
        600,
        min_value=0,
        label_zh="Gate 标记 TTL（秒）",
        label_en="Gate marker TTL (seconds)",
        label_ja="Gate マーカー TTL（秒）",
        desc_zh="gate marker 在磁盘上的过期时间",
        desc_en="Expiry for on-disk gate markers",
        desc_ja="ディスク上の gate マーカーの有効期限",
    ),
    _f(
        "gate.matcher",
        ("gate", "matcher"),
        "string",
        DEFAULT_GATE_MATCHER,
        label_zh="Gate 工具匹配器",
        label_en="Gate tool matcher",
        label_ja="Gate ツールマッチャー",
        desc_zh="正则：哪些工具名会触发 Gate（Cursor 安装时会扩展 Shell 等）。配置 .* 阻断全部工具",
        desc_en="Regex of tool names gated (Cursor install adds Shell, etc.). Use .* to gate all tools",
        desc_ja="Gate 対象ツール名の正規表現（Cursor では Shell 等を追加）。.* で全ツールを対象に",
    ),
    _f(
        "extract.mode",
        ("extract", "mode"),
        "enum",
        "manual",
        options=("manual", "async"),
        label_zh="提取模式",
        label_en="Extract mode",
        label_ja="抽出モード",
        desc_zh="manual：仅 CLI；async：会话结束自动排队",
        desc_en="manual: CLI only; async: queue on session end",
        desc_ja="manual: CLI のみ。async: セッション終了でキュー",
    ),
    _f(
        "extract.defer_when_active",
        ("extract", "defer_when_active"),
        "bool",
        False,
        label_zh="多会话时推迟提取",
        label_en="Defer extract when other sessions open",
        label_ja="他セッション中は抽出を延期",
        desc_zh="仍有活跃会话时不立刻 spawn extract",
        desc_en="Skip spawning extract while other sessions are active",
        desc_ja="他セッションが開いている間は extract を起動しない",
    ),
    _f(
        "llm.base_url",
        ("llm", "base_url"),
        "string",
        "",
        label_zh="LLM API 地址",
        label_en="LLM base URL",
        label_ja="LLM ベース URL",
        desc_zh="OpenAI 兼容端点，用于后台抽规则（留空则尝试 claude -p）",
        desc_en="OpenAI-compatible endpoint for background extract (empty tries claude -p)",
        desc_ja="バックグラウンド抽出用 OpenAI 互換 URL（空なら claude -p）",
    ),
    _f(
        "llm.model",
        ("llm", "model"),
        "string",
        "",
        label_zh="LLM 模型",
        label_en="LLM model",
        label_ja="LLM モデル",
        desc_zh="抽规则使用的模型名",
        desc_en="Model name for extraction",
        desc_ja="抽出用モデル名",
    ),
    _f(
        "llm.api_key",
        ("llm", "api_key"),
        "secret",
        "",
        label_zh="LLM API Key",
        label_en="LLM API key",
        label_ja="LLM API キー",
        desc_zh="留空表示不修改；仅在 config.toml 中保存",
        desc_en="Leave blank to keep unchanged; stored in config.toml only",
        desc_ja="空欄は変更なし。config.toml にのみ保存",
    ),
    _f(
        "embed.enabled",
        ("embed", "enabled"),
        "bool",
        False,
        label_zh="强制启用向量检索",
        label_en="Force embedding retrieval",
        label_ja="ベクトル検索を強制",
        desc_zh="为 true 时即使规则少于 20 条也尝试 embedding",
        desc_en="When true, try embedding even with fewer than 20 rules",
        desc_ja="true なら 20 件未満でも embedding を試行",
    ),
    _f(
        "embed.base_url",
        ("embed", "base_url"),
        "string",
        "",
        exclusive_group="embed_backend",
        exclusive_variant="remote",
        label_zh="Embedding API 地址",
        label_en="Embedding base URL",
        label_ja="Embedding ベース URL",
        desc_zh="配置后走远程 API；与本地模型互斥",
        desc_en="Use remote API; mutually exclusive with local model",
        desc_ja="リモート API を使用。ローカルモデルと排他",
    ),
    _f(
        "embed.model",
        ("embed", "model"),
        "string",
        "",
        exclusive_group="embed_backend",
        exclusive_variant="remote",
        label_zh="Embedding 模型",
        label_en="Embedding model",
        label_ja="Embedding モデル",
        desc_zh="远程 embedding 模型名",
        desc_en="Remote embedding model name",
        desc_ja="リモート embedding モデル名",
    ),
    _f(
        "embed.api_key",
        ("embed", "api_key"),
        "secret",
        "",
        exclusive_group="embed_backend",
        exclusive_variant="remote",
        label_zh="Embedding API Key",
        label_en="Embedding API key",
        label_ja="Embedding API キー",
        desc_zh="留空表示不修改",
        desc_en="Leave blank to keep unchanged",
        desc_ja="空欄は変更なし",
    ),
    _f(
        "embed.dimensions",
        ("embed", "dimensions"),
        "int",
        0,
        min_value=0,
        label_zh="向量维度",
        label_en="Embedding dimensions",
        label_ja="ベクトル次元",
        desc_zh="0 表示使用模型默认维度；远程 OpenAI 类模型可指定",
        desc_en="0 = model default; set for OpenAI text-embedding-3, etc.",
        desc_ja="0 はモデル既定。OpenAI 系では指定可",
    ),
    _f(
        "embed.chunk_size",
        ("embed", "chunk_size"),
        "int",
        4000,
        min_value=16,
        label_zh="分块大小",
        label_en="Chunk size",
        label_ja="チャンクサイズ",
        desc_zh="单条规则 embedding 分块字符数",
        desc_en="Characters per rule embedding chunk",
        desc_ja="ルール embedding の 1 チャンク文字数",
    ),
    _f(
        "embed.chunk_count",
        ("embed", "chunk_count"),
        "int",
        2,
        min_value=1,
        label_zh="分块数量",
        label_en="Chunk count",
        label_ja="チャンク数",
        desc_zh="每条规则最多分几块做向量",
        desc_en="Max chunks per rule for embedding",
        desc_ja="ルールあたりの最大チャンク数",
    ),
    _f(
        "embed.hook_timeout_seconds",
        ("embed", "hook_timeout_seconds"),
        "int",
        2,
        min_value=1,
        exclusive_group="embed_backend",
        exclusive_variant="local",
        label_zh="Hook 向量超时（秒）",
        label_en="Hook embed timeout (s)",
        label_ja="Hook ベクトルタイムアウト（秒）",
        desc_zh="热路径上等待本地 embed 服务的超时",
        desc_en="Timeout waiting for local embed server on hot path",
        desc_ja="ホットパスでローカル embed 待ちのタイムアウト",
    ),
    _f(
        "embed.server_idle_seconds",
        ("embed", "server_idle_seconds"),
        "int",
        3600,
        min_value=60,
        exclusive_group="embed_backend",
        exclusive_variant="local",
        label_zh="Embed 服务空闲关闭（秒）",
        label_en="Embed server idle shutdown (s)",
        label_ja="Embed サーバーアイドル終了（秒）",
        desc_zh="本地 embed 进程空闲多久后退出",
        desc_en="Exit local embed server after idle period",
        desc_ja="アイドル後にローカル embed プロセスを終了",
    ),
    _f(
        "embed.server_auto_start",
        ("embed", "server_auto_start"),
        "bool",
        True,
        exclusive_group="embed_backend",
        exclusive_variant="local",
        label_zh="自动启动 Embed 服务",
        label_en="Auto-start embed server",
        label_ja="Embed サーバー自動起動",
        desc_zh="需要本地向量时自动拉起 Unix socket 服务",
        desc_en="Spawn local embed server when needed",
        desc_ja="必要時にローカル embed サーバーを起動",
    ),
    _f(
        "hot_cache.enabled",
        ("hot_cache", "enabled"),
        "bool",
        True,
        label_zh="热缓存",
        label_en="Hot cache",
        label_ja="ホットキャッシュ",
        desc_zh="SessionStart 注入近期 HOT 规则摘要",
        desc_en="Inject recent HOT rules on session start",
        desc_ja="SessionStart で最近の HOT ルールを注入",
    ),
    _f(
        "session.idle_seconds",
        ("session", "idle_seconds"),
        "int",
        1800,
        min_value=60,
        label_zh="会话空闲阈值（秒）",
        label_en="Session idle threshold (s)",
        label_ja="セッションアイドル閾値（秒）",
        desc_zh="超过该时间无活动视为会话可结束",
        desc_en="Inactivity before a session is considered idle",
        desc_ja="非アクティブ後にセッションをアイドルとみなす時間",
    ),
    _f(
        "promotion.enabled",
        ("promotion", "enabled"),
        "bool",
        True,
        label_zh="跨项目提升",
        label_en="Cross-project promotion",
        label_ja="クロスプロジェクト昇格",
        desc_zh="多项目命中后自动升为 global 规则",
        desc_en="Promote rules to global after multi-project hits",
        desc_ja="複数プロジェクト命中後に global へ昇格",
    ),
)

SECTIONS: tuple[dict[str, Any], ...] = (
    {"id": "general", "field_ids": ("data_dir", "log_level", "max_injection_chars", "disabled", "strict", "dismiss_phrase")},
    {"id": "gate", "field_ids": ("gate.enabled", "gate.ttl_seconds", "gate.matcher")},
    {"id": "extract", "field_ids": ("extract.mode", "extract.defer_when_active")},
    {"id": "llm", "field_ids": ("llm.base_url", "llm.model", "llm.api_key")},
    {
        "id": "embed",
        "field_ids": (
            "embed.enabled",
            "embed.dimensions",
            "embed.chunk_size",
            "embed.chunk_count",
        ),
        "exclusive": {
            "group": "embed_backend",
            "variants": (
                {"id": "local", "field_ids": ("embed.server_auto_start", "embed.hook_timeout_seconds", "embed.server_idle_seconds")},
                {"id": "remote", "field_ids": ("embed.base_url", "embed.model", "embed.api_key")},
            ),
        },
    },
    {"id": "session", "field_ids": ("hot_cache.enabled", "session.idle_seconds", "promotion.enabled")},
)

SECTION_LABELS: dict[str, dict[Locale, str]] = {
    "general": {"zh": "常规", "en": "General", "ja": "一般"},
    "gate": {"zh": "Gate 阻断", "en": "Gate", "ja": "Gate"},
    "extract": {"zh": "规则提取", "en": "Extraction", "ja": "抽出"},
    "llm": {"zh": "LLM（后台抽规则）", "en": "LLM (background extract)", "ja": "LLM（バックグラウンド抽出）"},
    "embed": {"zh": "向量检索", "en": "Embedding", "ja": "ベクトル検索"},
    "session": {"zh": "会话与生命周期", "en": "Session & lifecycle", "ja": "セッションとライフサイクル"},
}

VARIANT_LABELS: dict[str, dict[Locale, str]] = {
    "local": {"zh": "本地模型", "en": "Local model", "ja": "ローカルモデル"},
    "remote": {"zh": "远程 API", "en": "Remote API", "ja": "リモート API"},
}

FIELD_BY_ID: dict[str, FieldDef] = {f.id: f for f in FIELDS}
